// Attendance PDF generation (WS-cert stage 1: the free Session Report).
//
// Split in two so the logic stays testable:
//   • buildReportModel(...)  — PURE. Normalizes attendance data into a render
//     model (rows, totals, meta, verification code). Fully unit-tested.
//   • renderReportPdf(model) — thin pdfkit pass that draws the model to bytes.
//
// A Unicode font (Noto Sans) is embedded when present so attendee names in
// Cyrillic / Greek / Vietnamese / accented Latin render correctly instead of as
// tofu boxes — the service now has users in many countries. CJK / Arabic need
// their own fonts and are a follow-up (see the cert spec).
const path = require('path');
const fs = require('fs');
const crypto = require('crypto');
const PDFDocument = require('pdfkit');

const FONT_PATH = path.join(__dirname, '..', '..', 'assets', 'fonts', 'NotoSans-Regular.ttf');
// Resolve once at load; if the font is somehow missing we fall back to pdfkit's
// built-in Helvetica rather than crashing (Latin-only, but never blank).
const UNICODE_FONT = fs.existsSync(FONT_PATH) ? FONT_PATH : null;

const DEFAULT_FOOTER = 'Generated by attendancetracker.dev';

// ─────────────────────────── pure helpers ───────────────────────────
function toDate(v) {
  if (!v) return null;
  const d = v instanceof Date ? v : new Date(v);
  return Number.isNaN(d.getTime()) ? null : d;
}

function durationMin(join, leave, fallbackEnd) {
  const j = toDate(join);
  if (!j) return 0;
  const l = toDate(leave) || toDate(fallbackEnd);
  if (!l) return 0;
  return Math.max(0, Math.round((l - j) / 60000));
}

function fmtDuration(min) {
  const m = Math.max(0, Math.round(min || 0));
  if (m < 60) return `${m}m`;
  const h = Math.floor(m / 60);
  const r = m % 60;
  return r ? `${h}h ${String(r).padStart(2, '0')}m` : `${h}h`;
}

// HH:MM in the meeting's timezone when given, else the server locale. Best-effort:
// a bad tz string falls back rather than throwing.
function fmtTime(v, tz) {
  const d = toDate(v);
  if (!d) return '—';
  try {
    return new Intl.DateTimeFormat('en-US', {
      hour: '2-digit', minute: '2-digit', hour12: false, timeZone: tz || undefined,
    }).format(d);
  } catch (_) {
    return new Intl.DateTimeFormat('en-US', { hour: '2-digit', minute: '2-digit', hour12: false }).format(d);
  }
}

function fmtDate(v, tz) {
  const d = toDate(v);
  if (!d) return '—';
  try {
    return new Intl.DateTimeFormat('en-US', {
      weekday: 'short', year: 'numeric', month: 'short', day: 'numeric', timeZone: tz || undefined,
    }).format(d);
  } catch (_) {
    return new Intl.DateTimeFormat('en-US', { year: 'numeric', month: 'short', day: 'numeric' }).format(d);
  }
}

function statusOf(p) {
  if (p.present) return 'Present';
  if (p.status) return String(p.status);
  return toDate(p.leaveTime ?? p.leaveTimeISO) ? 'Left' : 'Present';
}

// A short, stable, human-quotable code so a report can be referenced later.
// Deterministic (no randomness) → the same meeting always yields the same code,
// and it becomes the key for the public verify page in a later stage.
function verificationCode(seed) {
  const h = crypto.createHash('sha1').update(String(seed || 'x')).digest('hex').slice(0, 8).toUpperCase();
  return `AT-${h}`;
}

// PURE: normalize whatever attendance shape we were handed (persisted Firestore
// participants use joinTime/leaveTime Dates; the live client payload uses
// joinTimeISO/leaveTimeISO strings) into a flat render model.
function buildReportModel({ meeting = {}, attendees = [], options = {} } = {}) {
  const tz = meeting.timezone || null;
  const fallbackEnd = meeting.endTime || null;

  const rows = (attendees || []).map((p) => {
    const join = p.joinTime ?? p.joinTimeISO ?? null;
    const leave = p.leaveTime ?? p.leaveTimeISO ?? null;
    const mins = durationMin(join, leave, fallbackEnd);
    return {
      name: (p.displayName || p.name || 'Unknown').toString(),
      email: (p.email || '').toString(),
      joined: fmtTime(join, tz),
      left: leave ? fmtTime(leave, tz) : '—',
      active: fmtDuration(mins),
      activeMin: mins,
      status: statusOf(p),
    };
  });

  const presentCount = rows.filter((r) => r.status !== 'Absent' && r.status !== 'Excused').length;
  const brandName = options.brand && options.brand.name ? String(options.brand.name) : null;

  return {
    title: (meeting.title || 'Google Meet').toString(),
    date: fmtDate(meeting.startTime || meeting.date, tz),
    host: meeting.host ? String(meeting.host) : null,
    durationLabel: meeting.startTime && meeting.endTime
      ? fmtDuration(durationMin(meeting.startTime, meeting.endTime))
      : null,
    columns: ['Name', 'Email', 'Joined', 'Left', 'Active', 'Status'],
    rows,
    summary: {
      present: presentCount,
      total: rows.length,
      text: `${presentCount} of ${rows.length} recorded as present`,
    },
    footer: brandName ? `${brandName} · via attendancetracker.dev` : DEFAULT_FOOTER,
    verificationCode: verificationCode(
      options.verifySeed || `${meeting.conferenceId || ''}|${meeting.title || ''}|${meeting.startTime || ''}`,
    ),
  };
}

// ─────────────────────────── renderer ───────────────────────────
/* istanbul ignore next: exercised end-to-end in tests via the %PDF assertion,
   but the per-primitive pdfkit draw calls aren't worth line-by-line coverage. */
function renderReportPdf(model) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 50, info: { Title: `Attendance — ${model.title}` } });
      if (UNICODE_FONT) doc.registerFont('body', UNICODE_FONT);
      const font = UNICODE_FONT ? 'body' : 'Helvetica';
      const chunks = [];
      doc.on('data', (c) => chunks.push(c));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      const left = doc.page.margins.left;
      const right = doc.page.width - doc.page.margins.right;
      const width = right - left;

      // Header
      doc.font(font).fontSize(20).fillColor('#111827').text('Attendance Report', left, 50);
      doc.moveDown(0.2);
      doc.fontSize(13).fillColor('#374151').text(model.title, { width });
      doc.moveDown(0.4);
      doc.fontSize(10).fillColor('#6b7280');
      const metaBits = [model.date && `Date: ${model.date}`, model.host && `Host: ${model.host}`,
        model.durationLabel && `Duration: ${model.durationLabel}`].filter(Boolean);
      if (metaBits.length) doc.text(metaBits.join('     '), { width });
      doc.moveDown(0.2);
      doc.fillColor('#111827').fontSize(11).text(model.summary.text, { width });
      doc.moveDown(0.6);

      // Table
      const cols = [
        { key: 'name', label: 'Name', w: 0.26 },
        { key: 'email', label: 'Email', w: 0.28 },
        { key: 'joined', label: 'Joined', w: 0.11 },
        { key: 'left', label: 'Left', w: 0.11 },
        { key: 'active', label: 'Active', w: 0.11 },
        { key: 'status', label: 'Status', w: 0.13 },
      ];
      const xs = [];
      let acc = left;
      for (const c of cols) { xs.push(acc); acc += c.w * width; }

      const drawRow = (vals, { bold, y }) => {
        doc.font(font).fontSize(9).fillColor(bold ? '#111827' : '#374151');
        cols.forEach((c, i) => {
          doc.text(String(vals[c.key] ?? ''), xs[i] + 2, y, { width: c.w * width - 4, lineBreak: false, ellipsis: true });
        });
      };

      let y = doc.y;
      drawRow(Object.fromEntries(cols.map((c) => [c.key, c.label])), { bold: true, y });
      y += 14;
      doc.moveTo(left, y - 2).lineTo(right, y - 2).lineWidth(0.5).strokeColor('#d1d5db').stroke();
      y += 4;

      for (const r of model.rows) {
        if (y > doc.page.height - doc.page.margins.bottom - 40) { doc.addPage(); y = doc.page.margins.top; }
        drawRow(r, { bold: false, y });
        y += 13;
      }

      // Footer band on every page
      const range = doc.bufferedPageRange();
      for (let i = range.start; i < range.start + range.count; i++) {
        doc.switchToPage(i);
        const fy = doc.page.height - doc.page.margins.bottom + 8;
        doc.font(font).fontSize(8).fillColor('#9ca3af')
          .text(`${model.footer}   ·   Verification: ${model.verificationCode}`,
            left, fy, { width, align: 'center', lineBreak: false });
      }

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

// ─────────────────── per-attendee certificates (Pro) ───────────────────
// PURE: one certificate model per attendee who was actually present (absentees
// and excused are never certified). creditHours, when given, is a fixed value
// applied to all (typical for a fixed-length course/CLE session); otherwise the
// certificate states the individual's active duration.
function buildCertificateModels({ meeting = {}, attendees = [], options = {} } = {}) {
  const tz = meeting.timezone || null;
  const fallbackEnd = meeting.endTime || null;
  const session = (meeting.title || 'Google Meet').toString();
  const dateLabel = fmtDate(meeting.startTime || meeting.date, tz);
  const issuer = options.issuer ? String(options.issuer) : (meeting.host ? String(meeting.host) : null);
  const courseCode = options.courseCode ? String(options.courseCode) : null;
  const fixedCredit = Number(options.creditHours);
  const brandName = options.brand && options.brand.name ? String(options.brand.name) : null;
  const footer = brandName ? `${brandName} · via attendancetracker.dev` : DEFAULT_FOOTER;

  return (attendees || [])
    .filter((p) => {
      const s = statusOf(p);
      return s !== 'Absent' && s !== 'Excused';
    })
    .map((p) => {
      const join = p.joinTime ?? p.joinTimeISO ?? null;
      const leave = p.leaveTime ?? p.leaveTimeISO ?? null;
      const mins = durationMin(join, leave, fallbackEnd);
      return {
        name: (p.displayName || p.name || 'Attendee').toString(),
        session,
        dateLabel,
        durationLabel: fmtDuration(mins),
        creditHoursLabel: Number.isFinite(fixedCredit) && fixedCredit > 0
          ? `${fixedCredit} credit hour${fixedCredit === 1 ? '' : 's'}`
          : null,
        courseCode,
        issuer,
        footer,
        verificationCode: verificationCode(
          options.verifySeed
            ? `${options.verifySeed}|${p.email || p.displayName || ''}`
            : `${meeting.conferenceId || ''}|${p.email || p.displayName || ''}|${meeting.title || ''}`,
        ),
      };
    });
}

/* istanbul ignore next: layout primitives — exercised via the %PDF + page-count
   assertions in the tests, not worth per-draw-call coverage. */
function drawCertificate(doc, font, m) {
  const w = doc.page.width;
  const h = doc.page.height;
  // Double border
  doc.lineWidth(3).strokeColor('#1d4ed8').rect(24, 24, w - 48, h - 48).stroke();
  doc.lineWidth(0.75).strokeColor('#93c5fd').rect(34, 34, w - 68, h - 68).stroke();

  const cx = w / 2;
  doc.font(font).fillColor('#1e3a8a').fontSize(30).text('Certificate of Attendance', 0, 90, { width: w, align: 'center' });
  doc.fillColor('#374151').fontSize(13).text('This certifies that', 0, 150, { width: w, align: 'center' });
  doc.fillColor('#111827').fontSize(28).text(m.name, 0, 180, { width: w, align: 'center' });
  doc.fillColor('#374151').fontSize(13).text('attended', 0, 232, { width: w, align: 'center' });
  doc.fillColor('#111827').fontSize(18).text(m.session, 60, 258, { width: w - 120, align: 'center' });

  const detail = [
    m.dateLabel && `on ${m.dateLabel}`,
    m.creditHoursLabel ? `for ${m.creditHoursLabel}` : `for ${m.durationLabel}`,
  ].filter(Boolean).join('   ·   ');
  doc.fillColor('#374151').fontSize(13).text(detail, 0, 300, { width: w, align: 'center' });
  if (m.courseCode) doc.fillColor('#6b7280').fontSize(11).text(`Reference: ${m.courseCode}`, 0, 326, { width: w, align: 'center' });

  // Signature + issuer
  const sigY = h - 130;
  doc.lineWidth(0.75).strokeColor('#9ca3af').moveTo(cx - 130, sigY).lineTo(cx + 130, sigY).stroke();
  doc.fillColor('#374151').fontSize(11).text(m.issuer || 'Issued by the meeting host', 0, sigY + 6, { width: w, align: 'center' });

  // Footer band — includes the public verification URL so a registrar can confirm.
  doc.fillColor('#9ca3af').fontSize(8)
    .text(`${m.footer}   ·   Verify at attendancetracker.dev/verify.html?c=${m.verificationCode}`, 0, h - 60, { width: w, align: 'center' });
}

/* istanbul ignore next: thin pdfkit shell, asserted structurally in tests. */
function renderCertificatesPdf(models) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', layout: 'landscape', margin: 0 });
      if (UNICODE_FONT) doc.registerFont('body', UNICODE_FONT);
      const font = UNICODE_FONT ? 'body' : 'Helvetica';
      const chunks = [];
      doc.on('data', (c) => chunks.push(c));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      const list = models && models.length ? models : [];
      if (!list.length) {
        doc.font(font).fontSize(14).fillColor('#374151').text('No eligible attendees to certify.', 60, 60);
      } else {
        list.forEach((m, i) => { if (i > 0) doc.addPage(); drawCertificate(doc, font, m); });
      }
      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

module.exports = {
  buildReportModel,
  renderReportPdf,
  buildCertificateModels,
  renderCertificatesPdf,
  // exported for unit tests
  _internals: { durationMin, fmtDuration, fmtTime, fmtDate, statusOf, verificationCode, UNICODE_FONT },
};
