// Unit tests for the attendance PDF builder. The pure model is asserted in
// detail; the pdfkit render is checked structurally (valid %PDF, non-trivial
// size, survives many rows + non-Latin names).
const { buildReportModel, renderReportPdf, _internals } = require('../../src/lib/certificate');

const BASE = {
  meeting: {
    title: 'Bio 101', conferenceId: 'abc-def-ghi',
    startTime: '2026-08-20T14:00:00Z', endTime: '2026-08-20T15:00:00Z',
    host: 'Dr. Smith', timezone: 'UTC',
  },
  attendees: [
    { displayName: 'Ada', email: 'ada@x.com', joinTimeISO: '2026-08-20T14:00:00Z', leaveTimeISO: '2026-08-20T14:50:00Z', present: false },
    { displayName: 'Grace', email: 'grace@x.com', joinTimeISO: '2026-08-20T14:05:00Z', present: true },
  ],
};

describe('buildReportModel (pure)', () => {
  test('rows, columns, summary', () => {
    const m = buildReportModel(BASE);
    expect(m.columns).toEqual(['Name', 'Email', 'Joined', 'Left', 'Active', 'Status']);
    expect(m.rows).toHaveLength(2);
    expect(m.rows[0]).toMatchObject({ name: 'Ada', email: 'ada@x.com', active: '50m', status: 'Left' });
    expect(m.rows[1]).toMatchObject({ name: 'Grace', status: 'Present', left: '—' });
    expect(m.summary).toMatchObject({ present: 2, total: 2, text: '2 of 2 recorded as present' });
  });

  test('free footer by default, branded footer for a Pro brand', () => {
    expect(buildReportModel(BASE).footer).toBe('Generated by attendancetracker.dev');
    const branded = buildReportModel({ ...BASE, options: { brand: { name: 'Acme U' } } });
    expect(branded.footer).toBe('Acme U · via attendancetracker.dev');
  });

  test('verification code is deterministic and formatted', () => {
    const a = buildReportModel(BASE).verificationCode;
    const b = buildReportModel(BASE).verificationCode;
    expect(a).toBe(b);
    expect(a).toMatch(/^AT-[0-9A-F]{8}$/);
  });

  test('timezone shifts the displayed join time', () => {
    expect(buildReportModel(BASE).rows[0].joined).toBe('14:00');
    const ny = buildReportModel({ ...BASE, meeting: { ...BASE.meeting, timezone: 'America/New_York' } });
    expect(ny.rows[0].joined).toBe('10:00');
  });

  test('empty attendees still builds a valid model', () => {
    const m = buildReportModel({ meeting: { title: 'x' }, attendees: [] });
    expect(m.summary).toEqual({ present: 0, total: 0, text: '0 of 0 recorded as present' });
    expect(m.rows).toEqual([]);
  });

  test('no args → safe defaults', () => {
    const m = buildReportModel();
    expect(m.title).toBe('Google Meet');
    expect(m.rows).toEqual([]);
    expect(m.footer).toBe('Generated by attendancetracker.dev');
  });

  test('absent/excused status is not counted as present', () => {
    const m = buildReportModel({
      meeting: { title: 't' },
      attendees: [
        { displayName: 'A', present: true },
        { displayName: 'B', present: false, status: 'Absent' },
        { displayName: 'C', present: false, status: 'Excused' },
      ],
    });
    expect(m.summary).toMatchObject({ present: 1, total: 3 });
  });
});

describe('_internals', () => {
  const { durationMin, fmtDuration, statusOf } = _internals;

  test('durationMin', () => {
    expect(durationMin('2026-08-20T14:00:00Z', '2026-08-20T14:30:00Z')).toBe(30);
    expect(durationMin(null, '2026-08-20T14:30:00Z')).toBe(0);
    expect(durationMin('2026-08-20T14:00:00Z', null, '2026-08-20T14:10:00Z')).toBe(10); // fallback end
    expect(durationMin('2026-08-20T14:00:00Z', null)).toBe(0); // no leave, no fallback
  });

  test('fmtDuration', () => {
    expect(fmtDuration(45)).toBe('45m');
    expect(fmtDuration(60)).toBe('1h');
    expect(fmtDuration(65)).toBe('1h 05m');
    expect(fmtDuration(0)).toBe('0m');
  });

  test('statusOf', () => {
    expect(statusOf({ present: true })).toBe('Present');
    expect(statusOf({ present: false, leaveTimeISO: '2026-08-20T14:00:00Z' })).toBe('Left');
    expect(statusOf({ present: false })).toBe('Present');
    expect(statusOf({ present: false, status: 'Excused' })).toBe('Excused');
  });
});

describe('renderReportPdf', () => {
  test('produces a valid PDF buffer (incl. a non-Latin name)', async () => {
    const m = buildReportModel({
      meeting: { title: 'T', startTime: '2026-08-20T14:00:00Z' },
      attendees: [{ displayName: 'Даниил Ковач', joinTimeISO: '2026-08-20T14:00:00Z', present: true }],
    });
    const buf = await renderReportPdf(m);
    expect(Buffer.isBuffer(buf)).toBe(true);
    expect(buf.slice(0, 5).toString('latin1')).toBe('%PDF-');
    expect(buf.length).toBeGreaterThan(1000);
  });

  test('many attendees paginate without error', async () => {
    const attendees = Array.from({ length: 80 }, (_, i) => ({
      displayName: `User ${i}`, email: `u${i}@x.com`, joinTimeISO: '2026-08-20T14:00:00Z', present: true,
    }));
    const buf = await renderReportPdf(buildReportModel({ meeting: { title: 'Big' }, attendees }));
    expect(buf.slice(0, 5).toString('latin1')).toBe('%PDF-');
  });
});
